# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Headshot' do
pod "Parse"
end

target 'HeadshotTests' do

end

target 'HeadshotUITests' do

end

